#!/usr/bin/env bash
# Gate: fail the CI if any commit in the history has a footer, trailer,
# or attribution line. Permanent rule from ~/.AGENTS.md.
set -euo pipefail

violated=""

while read -r sha; do
  body="$(git log --format=%B -n1 "$sha")"

  # 1. Real git trailers (co-authored-by, signed-off-by, etc.)
  if git interpret-trailers --parse <<< "$body" 2>/dev/null | grep -q .; then
    violated="${violated}
  ${sha}: trailers"
  fi

  # 2. Known attribution/footer prefixes as stand-alone lines.
  #    Line-anchored so mid-sentence mentions never trip the gate.
  while IFS= read -r line; do
    if echo "$line" | grep -qiE '^( +)?(co-authored-by|generated-with|generated-by|reviewd-by|approved-by|sign-off|footer|generated by)\b'; then
      violated="${violated}
  ${sha}: attribution line
    ${line}"
    fi
  done <<< "$body"

done < <(git rev-list --all)

if [ -n "$violated" ]; then
  echo "::error::Commit footer/trailer/attribution violation found:${violated}"
  exit 1
fi

echo "OK: no commit footers, trailers, or attribution lines."
